### PR TITLE
951 can model promises

### PR DESCRIPTION
**Pull request by retro**
This implements promise API for can.Model as mentioned in #951 . Docs are missing, but I'll add them if we agree on the implementation.

It adds the `.get` static function on the model which calls `.findOne` internally and returns a compute that holds the deferred object returned from the `.findOne` function. When this deferred is resolved or rejected compute is updated.

It also implements deferred state for the model instances which gets updated when `destroy` or `save` request is happening.

It has a demo similar to one in the `can/list/promise` plugin.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
@retro is this needed now that we have observable promises?  I'm closing, please let me know if we need to reopen.

**Comment by pYr0x** [comment]
i do not found any documentation of that?

**Comment by justinbmeyer** [comment]
I'm not sure where we would document this. Possibly stache.keys. The promises themselves are not observable by can.compute. Instead, the template engine creates a shim of the promise that is observable.

**Comment by daffl** [comment]
I was thinking of just creating a "Promises" page (in the Pages section at http://canjs.com/docs/can.stache.html) that talks about how to use it.

**Pull request closed without merging**
