### PR TITLE
Adds autorender and can-import

### PR DESCRIPTION
**Pull request by justinbmeyer**
#1387 #1390 #1386

However, testee is freezing locally. @daffl can you fix this?

### CODE REVIEW

**Comment by sykopomp** [comment]
I was working on this feature elsewhere, but I guess it's all yours now. See #1369. Nicer to use a parser anyway, I guess, and I like the explicit import tags and steal-based partial loading that PR supports. Would be nice to pull in that particular feature into here. Besides that, I guess may as well blow away that PR. The code was written based on the discussion at #1037.

I don't like automagic import any more than I would like magically trying to import can.Models based on their usage in JavaScript code: I think it's better to make it easy for people to specify modules to load, with explicit dependencies. But I don't really care about fighting about that. Can I just have a flag so I can disable that feature in my own projects?

**Comment by justinbmeyer** [comment]
@sykopomp 

> I like the explicit import tags and steal-based partial loading that PR supports. 

I know what you mean by "partial loading", but what do you mean by "explicit import tags"?  There are explicit import tags: `<can-import>`

> I don't like automagic import any more than I would like magically trying to import can.Models based on their usage in JavaScript code

What do you mean?

**Comment by justinbmeyer** [comment]
> I like the explicit import tags and steal-based partial loading that PR supports.

Actually, I'm not sure what you mean.  Do you mean my PR or yours?

> Nicer to use a parser anyway, I guess

There's nothing to guess about.  It's supporting an intermediate representation of the parsed output.  It haves the time to a "first" render.  Which will make production bundles faster.

**Comment by daffl** [comment]
This is already in minor with the correct history.

**Pull request closed without merging**
