### PR TITLE
registerSimpleHelper

### PR DESCRIPTION
**Pull request by daffl**
This pull request adds `registerSimpleHelper` functionality to Mustache and Stache including tests and documentation.

### CODE REVIEW

**Comment by daffl** [comment]
Minor

**Comment by imjoshdean** [comment]
What's the benefit of a simple handler over a regular handler?

**Comment by matthewp** [comment]
Simple helpers you get the values and not computes. If you've written code like this:

```js
helpers: {
  addOne: function(val) {
    val = val.isComputed ? val() : val;
    return val + 1;
  }
}
```

Then you'd probably like a simpleHelper.

**Comment by imjoshdean** [comment]
Oh, neat! So basically quick and dirty helpers that have zero liability of live binding?

**Pull request closed without merging**
