### PR TITLE
Fixes a couple docs Issues

### PR DESCRIPTION
**Pull request by julia-allyce**
https://github.com/bitovi/canjs.com/issues/237
https://github.com/bitovi/canjs.com/issues/236

### CODE REVIEW

**Comment by daffl** [comment]
Thank you!

**Comment by moschel** [comment]
@daffl @julia-allyce is this not yet merged into the site because its waiting for the 2.2 release?

**Comment by daffl** [comment]
The site won't be deployed until the release.

**Comment by moschel** [comment]
@julia-allyce next time if you say "fixes bitovi/canjs.com#237" or "fixes #1672" or whatever the issue number is, it will close the ticket automatically when the PR is merged into master.

**Pull request merged**
